name = "aether-scrolls"
account_id = "74b94b7ffc15701b77e53f81bea03813"
compatibility_date = "2025-04-29"

[[ d1_databases ]]
binding = "arsenal_db"  # <-- MUST match what your code uses (lowercase)
database_name = "arsenal_db"
database_id = "ce7671fc-94b4-4dee-9ca0-53300c428fa2"

